# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import resources.images
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -1, 811, 571))
        self.label.setStyleSheet("border-image: url(:/1/image/background.png);\n"
"selection-color: rgb(0, 0, 0);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(210, 260, 241, 31))
        self.lineEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(1, 58, 125);")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 580, 581, 16))
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 110, 301, 131))
        self.label_3.setStyleSheet("border-image: url(:/1/image/logo.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(460, 260, 83, 31))
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.PB_Choose = QtWidgets.QPushButton(self.centralwidget)
        self.PB_Choose.setGeometry(QtCore.QRect(410, 266, 31, 20))
        self.PB_Choose.setObjectName("PB_Choose")
        self.PB_run = QtWidgets.QPushButton(self.centralwidget)
        self.PB_run.setGeometry(QtCore.QRect(550, 260, 61, 31))
        self.PB_run.setObjectName("PB_run")
        MainWindow.setCentralWidget(self.centralwidget)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "主界面"))
        self.label_2.setText(_translate("MainWindow", "@2020 何嘉琛、郝健翔、徐江、辛家豪、姚易甫、李南峰、郭鹏、常眉开 设计制作"))
        self.comboBox.setItemText(0, _translate("MainWindow", "银行卡🏦"))
        self.comboBox.setItemText(1, _translate("MainWindow", "身份证📇"))
        self.PB_Choose.setText(_translate("MainWindow", "..."))
        self.PB_run.setText(_translate("MainWindow", "识别"))
        self.action.setText(_translate("MainWindow", "关于我们"))

